### ISSUE TITLE
plugin returned with error: No path found

### ISSUE THREAD

**Issue by andradei** [panekj/lapce-go#16]
Windows 11, updated
Latest 0.2.8

This is the error I'm getting when opening Lapce on a go project:

![image](https://github.com/lapce-community/lapce-go/assets/2653546/d2f0beb7-71d2-4b32-93c9-0f91ea059a01)

**Comment by sid3r** [comment]
Go language server seems to be absent from your system. gopls needs to be installed.

**Comment by andradei** [comment]
I though the extension would take care of installing the go programs including gopls
