### ISSUE TITLE
plugin not working?

### ISSUE THREAD

**Issue by vintingb** [panekj/lapce-go#2]
Lapce version: v0.2.1
Os: windows 11

When I open a go mod project,go to definition not working,auto completion not woking, even though gopls not working

**Comment by panekj** [comment]
It won't work if you don't have gopls in `GOPATH`/`GOBIN` or set custom path to `gopls` in settings

**Comment by vintingb** [comment]
Actually I have gopls in GOPATH, but it not working. I also tried set gopls path in lapce setting, not working, and I checked the log:

[wasmtime::linker][WARN] command module exporting '__heap_base' is deprecated
[wasmtime::linker][WARN] command module exporting '__data_end' is deprecated
