### ISSUE TITLE
Is gofmt supported?

### ISSUE THREAD

**Issue by malmod** [panekj/lapce-go#4]
I tried "Format document" using `v2022.11.10` but it doesn't update the buffer.

**Comment by panekj** [comment]
yes

[2022-11-24 at 13.41.18 - Blue Coral.webm](https://user-images.githubusercontent.com/50457605/203787853-d5c731a6-3ff2-4595-961f-6a4efa28dd0a.webm)

**Comment by malmod** [comment]
Thanks! So maybe a GOPATH issue or something?

**Comment by rszyma** [comment]
If you are used to vscode "format on save" there's an option for that in lapce (settings > editor settings > format on save), but it's not enabled by default like in vscode.

(this comment may seem unrelated, but I thought that formatting was not working, I hope this comment helps someone)
