### ISSUE TITLE
Add set up and troubleshoot instruction

### ISSUE THREAD

**Issue by psydvl** [panekj/lapce-go#5]
I've had `v2022.11.10` installed on Lapce v0.2.4
In `$GOPATH/bin` is gopls v0.10.1
But it's not working
I've tried to set server path, but it's not works too
And nothing related on log except
```
[2022-11-24][20:01:36][wasmtime::linker][WARN] command module exporting '__heap_base' is deprecated
[2022-11-24][20:01:36][wasmtime::linker][WARN] command module exporting '__data_end' is deprecated
```

Can you provide any instructions to this thing?
Both for setting up and troubleshooting
Also, where can I change gopls settings (I prefer `gofumpt` to `gofmt`)?

System: openSUSE Tumbleweed

**Comment by isaacszf** [comment]
I'm having the same problem as @psydvl 

golps - v0.10.1
lapce - v0.2.4
lapce-go - v2022.11.10

OS: Windows 11 (Ubuntu WSL)

**Comment by panekj** [comment]
Should be fixed
