### ISSUE TITLE
plugin not working?

### ISSUE THREAD

**Issue by jeremyxu2010** [panekj/lapce-go#6]
Do not see any go language server feature described in here(https://github.com/golang/tools/tree/master/gopls). Is the plugin really working? 

version info:
lapce version: 0.2.4
lapce go version: v2022.11.10
go version: go1.19.3 darwin/arm64
gopls version: v0.10.1

**Comment by crab21** [comment]
the same issues ,it can't work, i have only one workspace, but always remind this「use multi workspace」
<img width="373" alt="image" src="https://user-images.githubusercontent.com/17155845/204310246-52c8c744-96c6-40f7-ae9b-35bb026f327f.png">

**Comment by Serdnad** [comment]
I'm not sure where crab21 was seeing that, but in my case, to get the plugin to work I had to explicitly point to my `gopls` installation under the plugin's settings.

<img width="304" alt="Screen Shot 2023-01-01 at 3 27 51 AM" src="https://user-images.githubusercontent.com/4723453/210165066-e64bcd22-e34f-4b20-b765-b4bffd82f62f.png">

**Comment by AndreasPB** [comment]
I get this when installing/reloading the plugin:
![image](https://user-images.githubusercontent.com/43907402/211884250-ad63d3f3-af4c-4095-9ad3-a731585d08be.png)

lapce version: 0.2.5
lapce go version: v2022.11.10
go version: go1.19.3 windows/amd64
gopls version: v0.10.1

**Comment by panekj** [comment]
It's most likely due to missing `GOROOT`/`GOBIN`
