### ISSUE TITLE
Implementation of interface functions support

### ISSUE THREAD

**Issue by sandeepyadavhas** [panekj/lapce-go#7]
As I can see gopls does support go to implementation of interface functions, by following command:

`gopls implementation a/b/path-to-file.go:100:12`
where 100 is line number and 12 is column number.

Is this feature already available in lapce-go?, and I might have missed it.
Cause I'm getting redirected to interface and back to calling of that interface function, when I do go to definition.

If this is not implemented, I was thinking of implementing it as an onboarding to lapce plugins.

**Comment by panekj** [comment]
This is not plugin implementation details, it depends on Lapce LSP client capabilities
